name: 'trigger-issue-action'
description: 'Create issue on matching text'
author: 'sei-jmattson'

inputs:
  trigger:
    description:
      'The text on which to trigger. Text following trigger is included in issue
      body.'
    required: true
    default: '/drr'

  repo:
    description:
      'The destination repo for the issue. If blank, posts to PR head repo.'

  title:
    description: 'The issue title'
    required: true
    default: 'Doc Review Required'

outputs:
  posted:
    description: 'True if issue posted'

runs:
  using: node20
  main: dist/index.js
